import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/components/theme/theme-provider";
import { NavigationHeader } from "@/components/shared/Header";

export const metadata: Metadata = {
  title: "Daeneris",
  description: "Generated by DaenerisAI",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <html lang="en" suppressHydrationWarning>
        <head>
          <link rel="icon" href="/images/Daeneris_logo_svg.svg" />
          <meta name="google-site-verification" content="7uZFp8WyXeWp42KBMpdQe85tz1eJclIcKvFFxKUSGY4" />
          <meta name="google-site-verification" content="GUAEtnrNkcMl-DNhGHWfrWY1hcLDepUrgM0-p9T9NE8" />
        </head>
        <body>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <NavigationHeader />
            {children}
          </ThemeProvider>
        </body>
      </html>
    </>
  )
}
